'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {ClipboardList,Users,Package,WalletCards,Camera,CheckCircle2,Play,UserRound,LogOut,Plus,ArrowLeft,ShieldCheck} from 'lucide-react';

type Status='New'|'Assigned'|'In Progress'|'Completed'|'Cancelled';
type Activity={time:string;text:string};
type WorkOrder={id:string;customer:string;address:string;date:string;employee:string;instructions:string;status:Status;notes:string;before:string[];after:string[];activity:Activity[]};
const seed:WorkOrder[]=[
{id:'WO-1001',customer:'Demo Office Center',address:'125 Business Park Dr, Demo City',date:'Aug 22, 2026',employee:'Jordan Lee',instructions:'Lobby, restrooms, breakroom and high-touch surface cleaning.',status:'Assigned',notes:'Use side service entrance after 5 PM.',before:[],after:[],activity:[{time:'9:10 AM',text:'Work order created'},{time:'9:14 AM',text:'Jordan Lee assigned'}]},
{id:'WO-1002',customer:'Sample Medical Suite',address:'440 Commerce Way, Demo City',date:'Aug 23, 2026',employee:'Taylor Reed',instructions:'Routine evening cleaning. Do not enter locked storage room.',status:'New',notes:'',before:[],after:[],activity:[{time:'Yesterday',text:'Work order created'}]},
{id:'WO-1003',customer:'Example Retail Store',address:'88 Market Street, Demo City',date:'Aug 20, 2026',employee:'Jordan Lee',instructions:'Floors, glass entry, restroom and waste removal.',status:'Completed',notes:'Completed without issue.',before:['Before photo'],after:['After photo'],activity:[{time:'Aug 20',text:'Work order created'},{time:'6:03 PM',text:'Work started'},{time:'7:12 PM',text:'Before/after photos uploaded'},{time:'7:28 PM',text:'Work completed'}]}
];
const styles={shell:{minHeight:'100vh',background:'#f5f7fb',color:'#0b2a55'} as const,top:{background:'#082a57',color:'#fff',padding:'12px 20px',display:'flex',gap:12,justifyContent:'space-between',alignItems:'center',flexWrap:'wrap' as const},bar:{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap' as const},btn:{border:0,borderRadius:10,padding:'10px 14px',fontWeight:800,cursor:'pointer'} as const,card:{background:'#fff',border:'1px solid #dce3ed',borderRadius:16,padding:18,boxShadow:'0 8px 24px rgba(8,42,87,.06)'} as const};
function badge(s:Status){const bg=s==='Completed'?'#ddf7e8':s==='In Progress'?'#fff2bd':s==='Cancelled'?'#fce1e1':'#e7effb';return <span style={{background:bg,padding:'6px 10px',borderRadius:999,fontSize:12,fontWeight:800}}>{s}</span>}
export default function DemoOps(){
 const [role,setRole]=useState<'admin'|'employee'>('admin'); const [tab,setTab]=useState('dashboard'); const [orders,setOrders]=useState(seed); const [selected,setSelected]=useState<string|null>(null); const [notice,setNotice]=useState('');
 const [form,setForm]=useState({customer:'New Demo Customer',address:'100 Demo Plaza',date:'Aug 26, 2026',employee:'Jordan Lee',instructions:'Standard commercial cleaning service.'});
 const wo=orders.find(x=>x.id===selected)||null; const assigned=useMemo(()=>orders.filter(x=>x.employee==='Jordan Lee'),[orders]);
 const update=(id:string,patch:Partial<WorkOrder>,activity?:string)=>setOrders(v=>v.map(x=>x.id===id?{...x,...patch,activity:activity?[...x.activity,{time:new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),text:activity}]:x.activity}:x));
 const create=()=>{const id='WO-'+(1000+orders.length+1);setOrders(v=>[{id,...form,status:'Assigned',notes:'',before:[],after:[],activity:[{time:'Now',text:'Work order created'},{time:'Now',text:`${form.employee} assigned`}]} as WorkOrder,...v]);setNotice(`${id} created and assigned.`);setTab('workorders')};
 const photo=(kind:'before'|'after')=>{if(!wo)return;const arr=kind==='before'?[...wo.before,`Before photo ${wo.before.length+1}`]:[...wo.after,`After photo ${wo.after.length+1}`];update(wo.id,kind==='before'?{before:arr}:{after:arr},`${kind==='before'?'Before':'After'} photo uploaded`)};
 const nav=role==='admin'?[['dashboard','Dashboard',ClipboardList],['workorders','Work Orders',ClipboardList],['customers','Customers',Users],['products','Products',Package],['payments','Orders / Payments',WalletCards]]:[['mywork','My Work Orders',ClipboardList],['profile','Profile',UserRound]];
 return <div style={styles.shell}>
  <header style={styles.top}><div><b style={{fontSize:20}}>CJPS LLC SERVICES</b><div style={{fontSize:12,opacity:.75}}>Interactive customer walkthrough • demo data only</div></div><div style={styles.bar}><button onClick={()=>{setRole('admin');setTab('dashboard');setSelected(null)}} style={{...styles.btn,background:role==='admin'?'#ffc400':'#fff',color:'#082a57'}}>Admin Demo</button><button onClick={()=>{setRole('employee');setTab('mywork');setSelected(null)}} style={{...styles.btn,background:role==='employee'?'#ffc400':'#fff',color:'#082a57'}}>Employee Demo</button><Link href='/' style={{...styles.btn,background:'transparent',color:'#fff',textDecoration:'none',border:'1px solid rgba(255,255,255,.35)'}}>Public Site</Link></div></header>
  <div style={{display:'grid',gridTemplateColumns:'minmax(180px,230px) 1fr',minHeight:'calc(100vh - 72px)'}}>
   <aside style={{background:'#fff',borderRight:'1px solid #dce3ed',padding:16}}><div style={{fontSize:12,fontWeight:900,color:'#6f7d90',margin:'8px 8px 14px'}}>{role==='admin'?'ADMIN':'EMPLOYEE'}</div>{nav.map(([key,label,Icon]:any)=><button key={key} onClick={()=>{setTab(key);setSelected(null)}} style={{width:'100%',display:'flex',gap:10,alignItems:'center',padding:'12px 10px',marginBottom:6,border:0,borderRadius:10,background:tab===key?'#eaf1fb':'transparent',color:'#0b2a55',fontWeight:800,cursor:'pointer'}}><Icon size={18}/>{label}</button>)}<button style={{width:'100%',display:'flex',gap:10,alignItems:'center',padding:'12px 10px',marginTop:20,border:0,background:'transparent',color:'#667',fontWeight:700}}><LogOut size={18}/>Logout</button></aside>
   <main style={{padding:'clamp(16px,3vw,34px)',overflow:'hidden'}}>
   {notice&&<div style={{background:'#e4f7eb',border:'1px solid #9dddb6',padding:12,borderRadius:10,marginBottom:16,fontWeight:700}}>{notice}</div>}
   {selected&&wo?<WorkOrderDetail wo={wo} role={role} update={update} photo={photo} back={()=>setSelected(null)}/>:
   role==='admin'?
    <>
    {tab==='dashboard'&&<><h1 style={{marginTop:0}}>Operations Dashboard</h1><p>Simple visibility into today&apos;s cleaning operations.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:14,margin:'22px 0'}}>{[['Open Work Orders',orders.filter(x=>x.status!=='Completed'&&x.status!=='Cancelled').length],['In Progress',orders.filter(x=>x.status==='In Progress').length],['Completed',orders.filter(x=>x.status==='Completed').length],['Unpaid Invoices',2]].map(([a,b])=><div key={String(a)} style={styles.card}><div style={{fontSize:13,color:'#6f7d90',fontWeight:800}}>{a}</div><div style={{fontSize:34,fontWeight:900,marginTop:8}}>{b}</div></div>)}</div><div style={styles.card}><h2>Upcoming Work</h2><OrderTable orders={orders.slice(0,3)} open={setSelected}/></div></>}
    {tab==='workorders'&&<><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h1 style={{marginBottom:4}}>Work Orders</h1><p>Create, assign and track cleaning jobs.</p></div><button style={{...styles.btn,background:'#ffc400',color:'#082a57'}} onClick={()=>setTab('newwo')}><Plus size={16} style={{verticalAlign:'middle'}}/> New Work Order</button></div><div style={styles.card}><OrderTable orders={orders} open={setSelected}/></div></>}
    {tab==='newwo'&&<div style={{maxWidth:760}}><button onClick={()=>setTab('workorders')} style={{...styles.btn,background:'transparent',color:'#082a57',paddingLeft:0}}><ArrowLeft size={16}/> Back</button><h1>Create Work Order</h1><div style={styles.card}><FormField label='Customer' value={form.customer} onChange={v=>setForm({...form,customer:v})}/><FormField label='Service Address' value={form.address} onChange={v=>setForm({...form,address:v})}/><FormField label='Service Date' value={form.date} onChange={v=>setForm({...form,date:v})}/><FormField label='Assigned Employee' value={form.employee} onChange={v=>setForm({...form,employee:v})}/><FormField label='Job Instructions' value={form.instructions} onChange={v=>setForm({...form,instructions:v})}/><button onClick={create} style={{...styles.btn,background:'#ffc400',color:'#082a57'}}>Create & Assign</button></div></div>}
    {tab==='customers'&&<SimpleList title='Customers' rows={[['Demo Office Center','Commercial customer'],['Sample Medical Suite','Commercial customer'],['Example Retail Store','Commercial customer']]} button='Add Customer'/>}
    {tab==='products'&&<SimpleList title='Products' rows={[['Commercial Disinfectant','$24.99 • Chemicals'],['Heavy-Duty Trash Bags','$29.99 • Paper Products'],['Microfiber Mop Kit','$59.99 • Equipment'],['Nitrile Gloves','$12.99 • PPE']]} button='Add Product'/>}
    {tab==='payments'&&<SimpleList title='Orders / Payments' rows={[['INV-DEMO-1042','Demo Office Center • Paid • $425.00'],['INV-DEMO-1043','Example Retail Store • Unpaid • $285.00'],['WEB-DEMO-88','Supply order • Paid • $84.97']]} button='Create Payment Request'/>}
    </>:
    <>
     {tab==='mywork'&&<><h1 style={{marginTop:0}}>My Work Orders</h1><p>Jordan Lee • Assigned cleaning jobs</p><div style={styles.card}><OrderTable orders={assigned} open={setSelected}/></div></>}
     {tab==='profile'&&<div style={{maxWidth:650}}><h1>Profile</h1><div style={styles.card}><div style={{display:'flex',gap:14,alignItems:'center'}}><div style={{width:54,height:54,borderRadius:'50%',background:'#ffc400',display:'grid',placeItems:'center',fontWeight:900,fontSize:20}}>JL</div><div><b>Jordan Lee</b><div>Employee demo account</div></div></div><hr style={{border:0,borderTop:'1px solid #e5e9ef',margin:'20px 0'}}/><p><ShieldCheck size={18} style={{verticalAlign:'middle'}}/> Employee access is limited to assigned work orders in the real MVP.</p></div></div>}
    </>}
   </main>
  </div>
  <style>{`@media(max-width:760px){aside{display:none!important} main{grid-column:1/-1!important} div[style*="grid-template-columns: minmax(180px, 230px)"]{grid-template-columns:1fr!important} table{min-width:640px}}`}</style>
 </div>
}
function OrderTable({orders,open}:{orders:WorkOrder[];open:(id:string)=>void}){return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:650}}><thead><tr>{['Work Order','Customer','Date','Employee','Status',''].map(x=><th key={x} style={{textAlign:'left',padding:'12px 8px',fontSize:12,color:'#6f7d90',borderBottom:'1px solid #e5e9ef'}}>{x}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td style={{padding:'14px 8px',fontWeight:900}}>{o.id}</td><td>{o.customer}</td><td>{o.date}</td><td>{o.employee}</td><td>{badge(o.status)}</td><td><button onClick={()=>open(o.id)} style={{...styles.btn,padding:'8px 10px',background:'#082a57',color:'#fff'}}>Open</button></td></tr>)}</tbody></table></div>}
function WorkOrderDetail({wo,role,update,photo,back}:{wo:WorkOrder;role:'admin'|'employee';update:(id:string,p:Partial<WorkOrder>,a?:string)=>void;photo:(k:'before'|'after')=>void;back:()=>void}){return <div style={{maxWidth:920}}><button onClick={back} style={{...styles.btn,background:'transparent',color:'#082a57',paddingLeft:0}}><ArrowLeft size={16}/> Back</button><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h1 style={{marginBottom:5}}>{wo.id}</h1><div>{wo.customer} • {wo.date}</div></div>{badge(wo.status)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,marginTop:20}}><div style={styles.card}><h3>Job Information</h3><p><b>Location</b><br/>{wo.address}</p><p><b>Assigned employee</b><br/>{wo.employee}</p><p><b>Instructions</b><br/>{wo.instructions}</p><p><b>Notes</b><br/>{wo.notes||'No notes yet.'}</p>{role==='employee'&&<><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:16}}>{wo.status==='Assigned'&&<button onClick={()=>update(wo.id,{status:'In Progress'},'Work started')} style={{...styles.btn,background:'#ffc400',color:'#082a57'}}><Play size={16}/> Start Job</button>}{wo.status==='In Progress'&&<button onClick={()=>update(wo.id,{status:'Completed'},'Work completed')} style={{...styles.btn,background:'#0e7a45',color:'#fff'}}><CheckCircle2 size={16}/> Complete Job</button>}</div><label style={{display:'block',marginTop:18,fontWeight:800}}>Employee Notes</label><textarea value={wo.notes} onChange={e=>update(wo.id,{notes:e.target.value})} placeholder='Add job notes...' style={{width:'100%',minHeight:90,padding:10,border:'1px solid #cfd8e5',borderRadius:10,marginTop:6}}/></>}</div><div style={styles.card}><h3>Before / After Photos</h3><p style={{color:'#6f7d90',fontSize:13}}>Demo upload controls simulate the mobile workflow without sending files anywhere.</p><PhotoBox title='Before Photos' count={wo.before.length} onClick={()=>photo('before')}/><PhotoBox title='After Photos' count={wo.after.length} onClick={()=>photo('after')}/></div></div><div style={{...styles.card,marginTop:16}}><h3>Activity History</h3>{wo.activity.slice().reverse().map((a,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'90px 1fr',gap:12,padding:'10px 0',borderBottom:'1px solid #eef1f5'}}><span style={{fontSize:12,color:'#6f7d90'}}>{a.time}</span><b>{a.text}</b></div>)}</div></div>}
function PhotoBox({title,count,onClick}:{title:string;count:number;onClick:()=>void}){return <div style={{border:'1px dashed #aeb9c7',borderRadius:12,padding:14,marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10}}><div><b>{title}</b><div style={{fontSize:12,color:'#6f7d90'}}>{count} uploaded</div></div><button onClick={onClick} style={{...styles.btn,background:'#eaf1fb',color:'#082a57'}}><Camera size={16}/> Add Photo</button></div></div>}
function FormField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label style={{display:'block',fontWeight:800,marginBottom:14}}>{label}<input value={value} onChange={e=>onChange(e.target.value)} style={{display:'block',width:'100%',padding:11,border:'1px solid #cfd8e5',borderRadius:10,marginTop:6}}/></label>}
function SimpleList({title,rows,button}:{title:string;rows:string[][];button:string}){return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><h1>{title}</h1><button onClick={()=>alert('Demo action — this would open the create form in production.')} style={{...styles.btn,background:'#ffc400',color:'#082a57'}}>{button}</button></div><div style={styles.card}>{rows.map((r,i)=><div key={i} style={{padding:'14px 4px',borderBottom:i<rows.length-1?'1px solid #edf0f4':'none'}}><b>{r[0]}</b><div style={{color:'#6f7d90',marginTop:3}}>{r[1]}</div></div>)}</div></div>}
