-- CJPS MVP schema. Review in a non-production Supabase project before applying.
create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','employee');
create type public.work_status as enum ('New','Assigned','In Progress','Completed','Cancelled');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text, role public.user_role not null default 'employee', created_at timestamptz not null default now());
create table public.customers(id uuid primary key default gen_random_uuid(), name text not null, email text, phone text, service_address text, created_at timestamptz not null default now());
create table public.work_orders(id uuid primary key default gen_random_uuid(), work_order_no text unique not null, customer_id uuid references public.customers(id), service_address text not null, service_date date, assigned_employee uuid references public.profiles(id), instructions text, status public.work_status not null default 'New', employee_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.work_order_photos(id uuid primary key default gen_random_uuid(), work_order_id uuid not null references public.work_orders(id) on delete cascade, uploaded_by uuid not null references public.profiles(id), photo_type text not null check(photo_type in('before','after')), storage_path text not null, created_at timestamptz not null default now());
create table public.work_order_activity(id uuid primary key default gen_random_uuid(), work_order_id uuid not null references public.work_orders(id) on delete cascade, actor_id uuid references public.profiles(id), event_type text not null, detail text, created_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(), name text not null, category text not null check(category in('Chemicals','Paper Products','Equipment','PPE')), description text, price_cents integer not null check(price_cents>=0), active boolean not null default true, created_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(), stripe_checkout_session_id text unique, customer_email text, amount_cents integer not null default 0, payment_status text not null default 'unpaid', created_at timestamptz not null default now());
create table public.order_items(id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id), product_name text not null, quantity integer not null check(quantity>0), unit_price_cents integer not null check(unit_price_cents>=0));
create table public.invoice_refs(id uuid primary key default gen_random_uuid(), work_order_id uuid references public.work_orders(id), stripe_invoice_id text unique, status text not null default 'unpaid', created_at timestamptz not null default now());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
alter table public.profiles enable row level security; alter table public.customers enable row level security; alter table public.work_orders enable row level security; alter table public.work_order_photos enable row level security; alter table public.work_order_activity enable row level security; alter table public.products enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.invoice_refs enable row level security;
create policy "profile self or admin read" on public.profiles for select using(id=auth.uid() or public.is_admin());
create policy "admin customers" on public.customers for all using(public.is_admin()) with check(public.is_admin());
create policy "work orders admin or assigned read" on public.work_orders for select using(public.is_admin() or assigned_employee=auth.uid());
create policy "admin work orders write" on public.work_orders for all using(public.is_admin()) with check(public.is_admin());
create policy "assigned employee update work order" on public.work_orders for update using(assigned_employee=auth.uid()) with check(assigned_employee=auth.uid());
create policy "photos admin or assigned read" on public.work_order_photos for select using(public.is_admin() or exists(select 1 from public.work_orders w where w.id=work_order_id and w.assigned_employee=auth.uid()));
create policy "assigned employee upload photo" on public.work_order_photos for insert with check(uploaded_by=auth.uid() and exists(select 1 from public.work_orders w where w.id=work_order_id and w.assigned_employee=auth.uid()));
create policy "activity admin or assigned read" on public.work_order_activity for select using(public.is_admin() or exists(select 1 from public.work_orders w where w.id=work_order_id and w.assigned_employee=auth.uid()));
create policy "activity actor insert" on public.work_order_activity for insert with check(actor_id=auth.uid() and (public.is_admin() or exists(select 1 from public.work_orders w where w.id=work_order_id and w.assigned_employee=auth.uid())));
create policy "public active products" on public.products for select using(active=true or public.is_admin());
create policy "admin products write" on public.products for all using(public.is_admin()) with check(public.is_admin());
create policy "admin financial read" on public.orders for select using(public.is_admin()); create policy "admin item read" on public.order_items for select using(public.is_admin()); create policy "admin invoices" on public.invoice_refs for select using(public.is_admin());
-- Storage setup should create a PRIVATE bucket named work-order-photos. Add storage.objects policies scoped to work-order IDs after the bucket is created; never make this bucket public.